### ISSUE TITLE
Broken on head

### ISSUE THREAD

**Issue by twitchyliquid64** [dcoles/flipperzero-hello-rust#3]
I imagine theyve redone a bunch of the build system, but yeah the instructions no longer work:

```shell
(venv) flipperzero-chrootenv:xxx@xxx:/tmp/flipperzero-firmware$ ./fbt firmware_hello_rust
	LINK	build/f7-firmware-D/.extapps/hello_rust_d.elf
/nix/store/6gvjdldjgwxbyiwzj5awzhs1nm2my0bv-gcc-arm-embedded-10.3.1/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: --gc-sections requires a defined symbol root specified by -e or -u
collect2: error: ld returned 1 exit status
scons: *** [build/f7-firmware-D/.extapps/hello_rust_d.elf] Error 1
********** ERRORS **********
Failed building build/f7-firmware-D/.extapps/hello_rust_d.elf: Error 1
(venv) flipperzero-chrootenv:xxx@xxx:/tmp/flipperzero-firmware$ readelf -h build/f7-firmware-D/.extapps/hello_rust_d.elf
readelf: Error: 'build/f7-firmware-D/.extapps/hello_rust_d.elf': No such file
```

**Comment by twitchyliquid64** [comment]
One more thing, I figured out how to build rust faps without needing the flipperzero-firmware repo + toolchain. Ive gotten this example working and published it to https://github.com/twitchyliquid64/fz-rust.

**Comment by dcoles** [comment]
I just updated to the current HEAD (flipperdevices/flipperzero-firmware@76d38e832e2da86457d0114beb20b88b6dc24221) and was able to build successfully on both Windows and 

```
/nix/store/6gvjdldjgwxbyiwzj5awzhs1nm2my0bv-gcc-arm-embedded-10.3.1/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: --gc-sections requires a defined symbol root specified by -e or -u
```

Did you run `cargo build --release` in the `applications_user/hello_rust` directory before executing `fbt`? I've typically seen that error when the linker does not receive any input.

```
$ ./fbt firmware_hello_rust
        LINK    build/f7-firmware-D/.extapps/hello_rust_d.elf
        APPMETA build/f7-firmware-D/hello_rust.fap
        FAP     build/f7-firmware-D/hello_rust.fap
        APPCHK  build/f7-firmware-D/hello_rust.fap
$ rm -r applications_user/hello_rust/target/
$ ./fbt firmware_hello_rust
        LINK    build/f7-firmware-D/.extapps/hello_rust_d.elf
/home/dcoles/workspace/flipperzero-firmware/toolchain/x86_64-linux/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: --gc-sections requires a defined symbol root specified by -e or -u
collect2: error: ld returned 1 exit status
scons: *** [build/f7-firmware-D/.extapps/hello_rust_d.elf] Error 1
********** ERRORS **********
Failed building build/f7-firmware-D/.extapps/hello_rust_d.elf: Error 1
```

(You can also run `cargo make build` in the project directory which runs both the Cargo and fbt build steps)

**Comment by dcoles** [comment]
> One more thing, I figured out how to build rust faps without needing the flipperzero-firmware repo + toolchain. Ive gotten this example working and published it to https://github.com/twitchyliquid64/fz-rust.

That's pretty rad! If that's the case, I can probably skip the whole build-as-`staticlib`-then-link step and just output an elf file directly. You can use the [`target.<triple>.linker`](https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinker) option in `.cargo/config.toml` to invoke a custom linker or wrapper script.

**Comment by twitchyliquid64** [comment]
I wasnt able to get outputting directly as an ELF to work unfortunately. However (taking a page from your book) building as a staticlib (to get the `.a`) and then doing some [eldricht gcc incantations](https://github.com/twitchyliquid64/fz-rust/blob/main/build.sh#L8) seemed to do the trick.

I'll have to look into `target.<triple>.linker`, that seems like a good way to avoid a wrapper shell script!

**Comment by dcoles** [comment]
I'm going to assume I can close this, given you've been able to successfully provide a bunch of patches. 😁
